[project]
name = "backend"
version = "0.1.0"
description = "Backend for marketsentience"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "polygon-api-client>=1.15.4",
    "python-dotenv>=1.1.1",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
