[project]
name = "marketsentience"
version = "0.1.0"
description = "market sentiment analysis website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "datasets>=3.4.1",
    "mlflow>=2.21.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "torchmetrics>=1.7.0",
    "transformers>=4.50.1",
]
